name = "lapce-toml"
version = "0.0.0"
author = "panekj"
display-name = "TOML"
description = "TOML for Lapce"
wasm = "bin/lapce-toml.wasm"

[activation]
language = ["toml"]
workspace-contains = ["*/*.toml"]

[config."volt.serverPath"]
default = ""

[config."volt.serverArgs"]
default = [
  "lsp",
  "stdio"
]
